apiVersion: v1
kind: Pod
metadata:
  labels:
    run: backend
  name: backend
spec:
  containers:
    - image: andytheape/fortune-cookie-backend:latest
      name: fortune-cookie-backend
      resources: {}
      ports:
        - containerPort: 5000
  restartPolicy: Always