apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fortune-cookie
  labels:
    app: cookie-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: fortune-cookie-backend
        image: andytheape/fortune-cookie-backend:latest
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 9000