apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    name: backend
spec:
  containers:
  - name: backend
    image: andytheape/fortune-cookie-backend:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 9000
    restartPolicy: Always