apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
