apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: andytheape/fortune-cookie-frontend:latest
    imagePullPolicy: Always
    env:
    - name: BACKEND_PORT
      value: "9000"
    - name: BACKEND_DNS
      value: "backend-service"
    ports:
    - containerPort: 8080
    restartPolicy: Always