apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: fortune-cookie-frontend
        image: andytheape/fortune-cookie-frontend:latest
        env:
          - name: BACKEND_PORT
            value: "9000"
          - name: BACKEND_DNS
            value: "backend-service"
        ports:
        - containerPort: 8080