name: Main workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }} 
  docker_token: ${{ secrets.DOCKER_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Clone down repository
        uses: actions/checkout@v4
        
      # Step 2: Build Go frontend
      - name: Build Go frontend
        working-directory: ./frontend
        run: go build

      # Step 3: Build Go backend
      - name: Build Go backend
        working-directory: ./backend
        run: go build

      # Step 4: Run tests
      - name: Test
        working-directory: ./frontend
        run: go test

      # Step 5: Log in to DockerHub (or GitHub Container Registry)
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 6: Build and push the frontend Docker image
      - name: Build and push frontend Docker image
        run: |
          docker build -t docker_username/fortune-cookie-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push docker_username/fortune-cookie-frontend:latest

      # Step 7: Build and push the backend Docker image
      - name: Build and push backend Docker image
        run: |
          docker build -t docker_username/fortune-cookie-backend:latest -f ./backend/Dockerfile ./backend
          docker push docker_username/fortune-cookie-backend:latest

      # Step 8: Upload repository files as artifacts (Optional, if you need them for other jobs)
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  
  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      # Step 1: Pull the latest frontend Docker image from DockerHub (or GHCR)
      - name: Pull frontend Docker image
        run: |
          docker pull docker_username/fortune-cookie-frontend:latest

      # Step 2: Pull the latest backend Docker image from DockerHub (or GHCR)
      - name: Pull backend Docker image
        run: |
          docker pull docker_username/fortune-cookie-backend:latest

      # Step 3: Deploy the application using Docker Compose (or another strategy)
      - name: Deploy using Docker Compose
        run: |
          docker-compose up -d
