name: Main workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }} 
  docker_token: ${{ secrets.DOCKER_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Clone down repository
        uses: actions/checkout@v4
        
      # Step 2: Build Go frontend
      - name: Build Go frontend
        working-directory: ./frontend
        run: go build

      # Step 3: Build Go backend
      - name: Build Go backend
        working-directory: ./backend
        run: go build

      # Step 4: Run tests
      - name: Test
        working-directory: ./frontend
        run: go test
      
      # Step 5: Build Docker Image (backend and frontend together)
      - name: Build Docker Image
        run: docker build -t docker_username/fortune-cookie:latest .

      # Step 6: Log in to DockerHub (or GitHub Container Registry)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: docker_username
          password: docker_token

      # Step 7: Push Docker Image to DockerHub
      - name: Push Docker Image
        run: docker push docker_username/fortune-cookie:latest

      # Step 8: Upload repository files as artifacts (Optional, if you need them for other jobs)
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  
  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      # Step 1: Pull the latest Docker image from DockerHub (or GHCR)
      - name: Pull Docker image
        run: docker pull docker_username/fortune-cookie:latest

      # Step 2: Deploy the application using Docker Compose (or other strategy)
      - name: Deploy using Docker Compose
        run: docker-compose up -d
